# DECLARATION OF AUTHORSHIP
# AUTHOR: Abhinav Datta (2401CS30)
# The following code is a part of CS2206 Mini Project: 2 Pass Assembler Simplex ISA (2026)
server: src/main.c src/assemble.c src/emulate.c src/router.c
	gcc src/main.c src/assemble.c src/emulate.c src/router.c -Iinclude -o build/target/server 
